name: nag_ui
description: A new Flutter package project.
version: 0.0.1
homepage: https://example-pet-store.com/newtify # need to change

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
