name: nag_ui
description: A new Flutter package project.
version: 0.0.1
homepage: https://example-pet-store.com/newtify # need to change

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  get: ^5.0.0-release-candidate-4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
